# Generated by Django 3.0.8 on 2020-07-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200726_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Talk', 'In Talk'), ('Owned', 'Owned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Social Media', 'Social Media'), ('E-Commerce', 'E-Commerce'), ('E-Payment', 'E-Payment'), ('Telecom', 'Telecom'), ('Video Streaming', 'Video Streaming'), ('E-Reader', 'E-Reader')], max_length=200, null=True),
        ),
    ]
