# Generated by Django 3.0.8 on 2020-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200726_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Talk', 'In Talk'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
